# Generated by Django 4.1.5 on 2023-01-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='jawab',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='tanya',
        ),
    ]
